// Created by iWeb 3.0.4 local-build-20140905

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-5,5,10,120),url:'Liens_vers_dautres_sites_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'Liens_vers_dautres_sites_files/stroke_1.png'},{rect:new IWRect(5,-5,98,10),url:'Liens_vers_dautres_sites_files/stroke_2.png'},{rect:new IWRect(103,-5,11,10),url:'Liens_vers_dautres_sites_files/stroke_3.png'},{rect:new IWRect(103,5,11,120),url:'Liens_vers_dautres_sites_files/stroke_4.png'},{rect:new IWRect(103,125,11,10),url:'Liens_vers_dautres_sites_files/stroke_5.png'},{rect:new IWRect(5,125,98,10),url:'Liens_vers_dautres_sites_files/stroke_6.png'},{rect:new IWRect(-5,125,10,10),url:'Liens_vers_dautres_sites_files/stroke_7.png'}],new IWSize(108,130))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Liens_vers_dautres_sites_files/Liens_vers_dautres_sitesMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');Widget.onload();applyEffects()}
function onPageUnload()
{Widget.onunload();}
